apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: cbagade/kub-data-demo:2
          # passing environment variables
          env:
              # process.env.STORY_FOLDER in app.js
            - name: STORY_FOLDER
              # value: 'story'
              # now access from config map
              valueFrom: 
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc

# docker build -t cbagade/kub-data-demo:2 .
# docker push cbagade/kub-data-demo:2
# kubectl apply -f environment.yaml
# kubectl get cm
# kubectl apply -f host-pv.yaml
# kubectl apply -f host-pvc.yaml
# kubectl apply -f deployment.yaml -f service.yaml
# access GET 
# http://localhost:30004/story