apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  # pods with label app: story will be target for this service
  selector: 
    app: story
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
      nodePort: 30003
