apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # no need to reach from outside
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80